version: '3.8'

services:

# RabbitMQ
  stats:
    image: bitnami/rabbitmq
    container_name: stats
    mem_limit: 250 M
    environment:
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=user
      - RABBITMQ_NODE_TYPE=stats
      - RABBITMQ_NODE_NAME=rabbit@stats
      - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - 'stats_data:/bitnami'
    networks:
      - rmq-backend
  queue-disc1:
    image: bitnami/rabbitmq
    container_name: queue-disc1
    mem_limit: 250 M
    environment:
      - RABBITMQ_NODE_TYPE=queue-disc
      - RABBITMQ_NODE_NAME=rabbit@queue-disc1
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@stats
      - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
    volumes:
      - 'disc1_data:/bitnami'
    networks:
      - rmq-backend
  queue-ram1:
    image: bitnami/rabbitmq
    container_name: queue-ram1
    mem_limit: 250 M
    environment:
      - RABBITMQ_NODE_TYPE=queue-ram
      - RABBITMQ_NODE_NAME=rabbit@queue-ram1
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@stats
      - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
    volumes:
      - 'ram1_data:/bitnami'
    networks:
      - rmq-backend

volumes:
  stats_data:
    name: rmq_stats_data
    driver: local
  disc1_data:
    name: rmq_disc1_data
    driver: local
  ram1_data:
    name: rmq_ram1_data
    driver: local

networks:
  rmq-backend:
    name: rmq-backend-network
